# Google Cloud Platform Deployment Configuration
runtime: python311

# App Engine Configuration
service: verify-ai-backend
instance_class: F4_1G

# Auto-scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Environment variables
env_variables:
  PYTHON_VERSION: "3.11"
  ENVIRONMENT: "production"

# Handlers
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

# Health checks
readiness_check:
  path: "/api/v1/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/v1/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
